zend_extension=xdebug.so

; Xdebug 3 settings
xdebug.mode=debug,develop,coverage
xdebug.start_with_request=yes

; PhpStorm listens on this port
xdebug.client_port=9003

; Host machine from inside Docker
xdebug.client_host=172.17.0.1

; Optional but recommended
xdebug.log=/tmp/xdebug.log
xdebug.log_level=7

