  postgres:
    image: postgres:12.2
    volumes:
      - /var/lib/docker/postgres/${DB_DATABASE}:/var/lib/postgresql

    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
# Uncomment if you want it to be exposed system-wide.
#    db:
#      ports:
#        - 5432:5432
